version: 2
jobs:
  build:
    docker:
      - image: domslee/bazel:tbb
    steps:
      - checkout
      - run: >
          apt-get install software-properties-common -y;
          add-apt-repository ppa:jonathonf/gcc-9.0 -y;
          apt install gcc-9 g++-9 -y;
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9;
          bazel build //src:ew_get_moves;
          mkdir persist;
          cp -r /usr/local/include/tbb_build persist/tbb_build;
          cp -r bazel-bin/src persist/src;
      - persist_to_workspace:
          root: persist
          paths:
            - bazel-bin
            - tbb_build
  getMoveServiceTest:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          find /tmp/persist;
          mkdir -p /usr/local/include;
          find /usr/local/include;
          sudo cp -r /tmp/persist/tbb_build /usr/local/include/tbb_build;
          mkdir .docker/get-move-service/external_bin;
          sudo cp /tmp/persist/src/ew_get_moves .docker/get-move-service/external_bin/
      - run: >
          cd .docker/get-move-service;
          sudo pip install pipenv;
          pipenv install;
          pipenv run sh -c "cd src/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - getMoveServiceTest:
          requires:
            - build

