version: 2
jobs:
  build:
    docker:
      - image: domslee/bazel:tbb
    steps:
      - checkout
      - run: >
          apt-get install software-properties-common -y;
          add-apt-repository ppa:jonathonf/gcc-9.0 -y;
          apt install gcc-9 g++-9 -y;
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9;
          bazel build //src:ew_get_moves
      - persist_to_workspace:
          root: bazel-bin
          paths:
            - src
  getMoveServiceTest:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/bazel-bin
      - run: >
          mkdir .docker/get-move-service/external_bin;
          cp /tmp/bazel-bin/src/ew_get_moves .docker/get-move-service/external_bin/
      - run: >
          cd .docker/get-move-service;
          sudo pip install pipenv;
          pipenv install;
          pipenv run "cd src/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - getMoveServiceTest:
          requires:
            - build

