version: 2
jobs:
  build:
    docker:
      - image: domslee/bazel:tbb2
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{ .Branch }}
      - run: >
          bazel build //src:ew_get_moves;
          mkdir persist;
          cp -r /usr/local/include/tbb_build persist/tbb_build;
          cp -r /usr/local/include/tbb persist/tbb;
          cp -r bazel-bin/src persist/src;
      - persist_to_workspace:
          root: persist
          paths:
            - src
            - tbb_build
            - tbb
      - save_cache:
          keys:
            - build-{{ .Branch }}
            - build-force1
          paths:
            - bazel-bin
            - bazel-out
            - bazel-genfiles
            - bazel-tetrisai
            - bazel-project
            - bazel-testlogs
            - /root/.cache/bazel
  getMoveServiceTest:
    docker:
      - image: domslee/bazel:tbb2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          mkdir -p /usr/local/include;
          cp -r /tmp/persist/tbb_build /usr/local/include/tbb_build;
          cp -r /tmp/persist/tbb /usr/local/include/tbb;
          cp /tmp/persist/src/ew_get_moves .docker/get-move-service/src/external_bin/
      - run: >
          export LC_ALL=C.UTF-8;
          export LANG=C.UTF-8;
          apt-get update;
          apt-get install software-properties-common -y;
          add-apt-repository ppa:deadsnakes/ppa -y;
          apt-get update;
          apt-get install python3.7 python3-pip -y;
          cd .docker/get-move-service;
          python3.7 -m pip install pipenv --user;
          python3.7 -m pipenv install;
          find /usr/local/include;
          python3.7 -m pipenv run sh -c "cd src/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - getMoveServiceTest:
          requires:
            - build

