version: 2
jobs:
  getMoveServiceTest:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: >
          cd .docker/get-move-service;
          sudo pip install pipenv;
          pipenv install;
          pipenv run "cd src; ./rebuild.py";
          pipenv run "cd src/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - getMoveServiceTest

