version: 2
jobs:
  build:
    docker:
      - image: domslee/bazel:tbb2
    steps:
      - checkout
      - run: >
          bazel build //src:ew_get_moves;
          mkdir persist;
          cp -r /usr/local/include/tbb_build persist/tbb_build;
          cp -r /usr/local/include/tbb persist/tbb;
          cp -r bazel-bin/src persist/src;
      - persist_to_workspace:
          root: persist
          paths:
            - src
            - tbb_build
            - tbb
  getMoveServiceTest:
    docker:
      - image: domslee/bazel:tbb2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          mkdir -p /usr/local/include;
          cp -r /tmp/persist/tbb_build /usr/local/include/tbb_build;
          cp -r /tmp/persist/tbb /usr/local/include/tbb;
          cp /tmp/persist/src/ew_get_moves .docker/get-move-service/src/external_bin/
      - run: >
          apt-get update;
          apt-get install python3 python3-pip -y;
          cd .docker/get-move-service;
          python3 -m pip install pipenv --user;
          pipenv install;
          find /usr/local/include;
          pipenv run sh -c "cd src/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - getMoveServiceTest:
          requires:
            - build

