version: 2
jobs:
  build:
    docker:
      # ?
      - image: domslee/bazel:tbb22
    steps:
      - checkout
      - run: >
          cd cpp;
          ./scripts/setup.sh;
          bazel build //src/pso/main:get_moves;
          mkdir persist;
          cp -r bazel-bin/src persist/src;
      - persist_to_workspace:
          root: cpp/persist
          paths:
            - src
  getMoveServiceTest:
    docker:
      - image: domslee/bazel:tbb-pipenv
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          cp /tmp/persist/src/pso/main/get_moves get-move-service/src/external_bin/
      - run: >
          cd get-move-service;
          python3.7 -m pipenv install;
          python3.7 -m pipenv run sh -c "cd src/test; python -m unittest";
  pythonTest:
    docker:
      - image: domslee/bazel:tbb-pipenv
    steps:
      - checkout
      - run: >
          cd python;
          python3.7 -m pipenv install;
          python3.7 -m pipenv run sh -c "cd tetrisai/test; python -m unittest";
  cppTest:
    docker:
      - image: domslee/bazel:tbb22
    steps:
      - checkout
      - run: >
          cd cpp;
          export LD_LIBRARY_PATH=/usr/local/include/tbb_build;
          ./scripts/setup.sh;
          bazel query //... | xargs bazel test;
  webTest:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: >
          cd web/tetrisai-web;
          npm install;
          npm run test:unit;
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - pythonTest
      - getMoveServiceTest:
          requires:
            - build
      - cppTest:
          requires:
            - build
      - webTest

