version: 2
jobs:
  build:
    docker:
      - image: domslee/bazel:tbb2
    steps:
      - checkout
      - run: >
          cd cpp;
          bazel build //src/pso/main:ew_get_moves;
          mkdir persist;
          cp -r /usr/local/include/tbb_build persist/tbb_build;
          cp -r /usr/local/include/tbb persist/tbb;
          cp -r bazel-bin/src persist/src;
      - persist_to_workspace:
          root: persist
          paths:
            - src
            - tbb_build
            - tbb
  getMoveServiceTest:
    docker:
      - image: domslee/bazel:tbb-pipenv
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          mkdir -p /usr/local/include;
          cp -r /tmp/persist/tbb_build /usr/local/include/tbb_build;
          cp -r /tmp/persist/tbb /usr/local/include/tbb;
          cp /tmp/persist/src/pso/main/ew_get_moves get-move-service/src/external_bin/
      - run: >
          cd get-move-service;
          python3.7 -m pip install pipenv --user;
          python3.7 -m pipenv install;
          python3.7 -m pipenv run sh -c "cd src/test; python -m unittest";
  pythonTest:
    getMoveServiceTest:
    docker:
      - image: domslee/bazel:tbb-pipenv
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/persist
      - run: >
          mkdir -p /usr/local/include;
          cp -r /tmp/persist/tbb_build /usr/local/include/tbb_build;
          cp -r /tmp/persist/tbb /usr/local/include/tbb;
          cp /tmp/persist/src/pso/main/ew_get_moves get-move-service/src/external_bin/
      - run: >
          cd python;
          python3.7 -m pip install pipenv --user;
          python3.7 -m pipenv install;
          python3.7 -m pipenv run sh -c "cd tetrisai/test; python -m unittest";
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - getMoveServiceTest:
          requires:
            - build
      - pythonTest:
          requires:
            - build

