import { DemoEntry, DemoButton } from "../IDemoPlayer";
import { eventsForUnpressThenPress } from './utility';


export function getRightVsDown() {
  return rightVsDown.concat(eventsForUnpressThenPress(DemoButton.BUTTON_RIGHT, 492));
}


const rightVsDown: DemoEntry[] = [
  {
     'frame':270,
     'button':3,
     'isDown':true,
     'startFrame':270
  },
  {
     'frame':271,
     'button':3,
     'isDown':false,
     'startFrame':271
  },
  {
     'frame':275,
     'button':3,
     'isDown':true,
     'startFrame':275
  },
  {
     'frame':276,
     'button':3,
     'isDown':false,
     'startFrame':276
  },
  {
     'frame':280,
     'button':3,
     'isDown':true,
     'startFrame':280
  },
  {
     'frame':281,
     'button':3,
     'isDown':false,
     'startFrame':281
  },
  {
     'frame':285,
     'button':7,
     'isDown':true,
     'startFrame':285
  },
  {
     'frame':286,
     'button':7,
     'isDown':false,
     'startFrame':286
  },
  {
     'frame':290,
     'button':7,
     'isDown':true,
     'startFrame':290
  },
  {
     'frame':291,
     'button':7,
     'isDown':false,
     'startFrame':291
  },
  {
     'frame':295,
     'button':7,
     'isDown':true,
     'startFrame':295
  },
  {
     'frame':296,
     'button':7,
     'isDown':false,
     'startFrame':296
  },
  {
     'frame':300,
     'button':7,
     'isDown':true,
     'startFrame':300
  },
  {
     'frame':301,
     'button':7,
     'isDown':false,
     'startFrame':301
  },
  {
     'frame':305,
     'button':5,
     'isDown':true,
     'startFrame':305
  },
  {
     'frame':306,
     'button':5,
     'isDown':false,
     'startFrame':306
  },
  {
     'frame':311,
     'button':0,
     'isDown':true,
     'startFrame':311
  },
  {
     'frame':312,
     'button':3,
     'isDown':true,
     'startFrame':312
  },
  {
     'frame':318,
     'button':0,
     'isDown':false,
     'startFrame':318
  },
  {
     'frame':318,
     'button':3,
     'isDown':false,
     'startFrame':318
  },
  {
     'frame':467,
     'button':0,
     'isDown':true,
     'startFrame':467
  },
  {
     'frame':468,
     'button':0,
     'isDown':false,
     'startFrame':468
  },
  {
     'frame':474,
     'button':7,
     'isDown':true,
     'startFrame':474
  },
  {
     'frame':475,
     'button':7,
     'isDown':false,
     'startFrame':475
  },
  {
     'frame':476,
     'button':2,
     'isDown':false,
     'startFrame':476
  },
  {
     'frame':477,
     'button':2,
     'isDown':false,
     'startFrame':477
  },
  {
     'frame':478,
     'button':2,
     'isDown':false,
     'startFrame':478
  },
  {
     'frame':479,
     'button':2,
     'isDown':false,
     'startFrame':479
  },
  {
     'frame':480,
     'button':2,
     'isDown':false,
     'startFrame':480
  },
  {
     'frame':481,
     'button':2,
     'isDown':false,
     'startFrame':481
  },
  {
     'frame':482,
     'button':2,
     'isDown':false,
     'startFrame':482
  }
]