import { DemoButton, DemoEntry } from '../IDemoPlayer';
import { eventsForUnpressThenPress, eventsForSinglePress } from './utility';
import { getDemoEntry } from '../DemoEntryHelpers';


export function get19_9HighRight() {
   let events = lvl19_9highright;
   return events.concat(eventsForUnpressThenPress(DemoButton.BUTTON_LEFT, 851))
               .concat([
                  // appears 869
                  getDemoEntry(868, DemoButton.BUTTON_LEFT, true),
                  getDemoEntry(869, DemoButton.BUTTON_LEFT, false)
               ]);
}


const lvl19_9highright: DemoEntry[] = [
   {
      'frame':270,
      'button':3,
      'isDown':true,
      'startFrame':270
   },
   {
      'frame':271,
      'button':3,
      'isDown':false,
      'startFrame':271
   },
   {
      'frame':275,
      'button':3,
      'isDown':true,
      'startFrame':275
   },
   {
      'frame':276,
      'button':3,
      'isDown':false,
      'startFrame':276
   },
   {
      'frame':280,
      'button':3,
      'isDown':true,
      'startFrame':280
   },
   {
      'frame':281,
      'button':3,
      'isDown':false,
      'startFrame':281
   },
   {
      'frame':285,
      'button':7,
      'isDown':true,
      'startFrame':285
   },
   {
      'frame':286,
      'button':7,
      'isDown':false,
      'startFrame':286
   },
   {
      'frame':290,
      'button':7,
      'isDown':true,
      'startFrame':290
   },
   {
      'frame':291,
      'button':7,
      'isDown':false,
      'startFrame':291
   },
   {
      'frame':295,
      'button':7,
      'isDown':true,
      'startFrame':295
   },
   {
      'frame':296,
      'button':7,
      'isDown':false,
      'startFrame':296
   },
   {
      'frame':300,
      'button':7,
      'isDown':true,
      'startFrame':300
   },
   {
      'frame':301,
      'button':7,
      'isDown':false,
      'startFrame':301
   },
   {
      'frame':305,
      'button':5,
      'isDown':true,
      'startFrame':305
   },
   {
      'frame':306,
      'button':5,
      'isDown':false,
      'startFrame':306
   },
   {
      'frame':311,
      'button':0,
      'isDown':true,
      'startFrame':311
   },
   {
      'frame':312,
      'button':3,
      'isDown':true,
      'startFrame':312
   },
   {
      'frame':318,
      'button':0,
      'isDown':false,
      'startFrame':318
   },
   {
      'frame':318,
      'button':3,
      'isDown':false,
      'startFrame':318
   },
   {
      'frame':364,
      'button':6,
      'isDown':true,
      'startFrame':364
   },
   {
      'frame':365,
      'button':1,
      'isDown':true,
      'startFrame':365
   },
   {
      'frame':366,
      'button':6,
      'isDown':false,
      'startFrame':366
   },
   {
      'frame':367,
      'button':1,
      'isDown':false,
      'startFrame':367
   },
   {
      'frame':368,
      'button':6,
      'isDown':true,
      'startFrame':368
   },
   {
      'frame':369,
      'button':6,
      'isDown':false,
      'startFrame':369
   },
   {
      'frame':374,
      'button':6,
      'isDown':true,
      'startFrame':374
   },
   {
      'frame':375,
      'button':6,
      'isDown':false,
      'startFrame':375
   },
   {
      'frame':406,
      'button':6,
      'isDown':true,
      'startFrame':406
   },
   {
      'frame':407,
      'button':6,
      'isDown':false,
      'startFrame':407
   },
   {
      'frame':466,
      'button':6,
      'isDown':true,
      'startFrame':466
   },
   {
      'frame':467,
      'button':0,
      'isDown':true,
      'startFrame':467
   },
   {
      'frame':467,
      'button':6,
      'isDown':false,
      'startFrame':467
   },
   {
      'frame':469,
      'button':6,
      'isDown':true,
      'startFrame':469
   },
   {
      'frame':469,
      'button':0,
      'isDown':false,
      'startFrame':469
   },
   {
      'frame':470,
      'button':6,
      'isDown':false,
      'startFrame':470
   },
   {
      'frame':472,
      'button':6,
      'isDown':true,
      'startFrame':472
   },
   {
      'frame':472,
      'button':6,
      'isDown':false,
      'startFrame':472
   },
   {
      'frame':474,
      'button':6,
      'isDown':true,
      'startFrame':474
   },
   {
      'frame':475,
      'button':6,
      'isDown':false,
      'startFrame':475
   },
   {
      'frame':482,
      'button':6,
      'isDown':true,
      'startFrame':482
   },
   {
      'frame':484,
      'button':6,
      'isDown':false,
      'startFrame':484
   },
   {
      'frame':510,
      'button':6,
      'isDown':true,
      'startFrame':510
   },
   {
      'frame':511,
      'button':6,
      'isDown':false,
      'startFrame':511
   },
   {
      'frame':513,
      'button':6,
      'isDown':true,
      'startFrame':513
   },
   {
      'frame':514,
      'button':6,
      'isDown':false,
      'startFrame':514
   },
   {
      'frame':516,
      'button':6,
      'isDown':true,
      'startFrame':516
   },
   {
      'frame':517,
      'button':6,
      'isDown':false,
      'startFrame':517
   },
   {
      'frame':549,
      'button':0,
      'isDown':true,
      'startFrame':549
   },
   {
      'frame':551,
      'button':0,
      'isDown':false,
      'startFrame':551
   },
   {
      'frame':552,
      'button':0,
      'isDown':true,
      'startFrame':552
   },
   {
      'frame':554,
      'button':0,
      'isDown':false,
      'startFrame':554
   },
   {
      'frame':575,
      'button':6,
      'isDown':true,
      'startFrame':575
   },
   {
      'frame':576,
      'button':6,
      'isDown':false,
      'startFrame':576
   },
   {
      'frame':580,
      'button':6,
      'isDown':true,
      'startFrame':580
   },
   {
      'frame':581,
      'button':6,
      'isDown':false,
      'startFrame':581
   },
   {
      'frame':622,
      'button':6,
      'isDown':true,
      'startFrame':622
   },
   {
      'frame':623,
      'button':6,
      'isDown':false,
      'startFrame':623
   },
   {
      'frame':646,
      'button':7,
      'isDown':true,
      'startFrame':646
   },
   {
      'frame':647,
      'button':0,
      'isDown':true,
      'startFrame':647
   },
   {
      'frame':647,
      'button':7,
      'isDown':false,
      'startFrame':647
   },
   {
      'frame':648,
      'button':0,
      'isDown':false,
      'startFrame':648
   },
   {
      'frame':649,
      'button':0,
      'isDown':true,
      'startFrame':649
   },
   {
      'frame':652,
      'button':0,
      'isDown':false,
      'startFrame':652
   },
   {
      'frame':696,
      'button':7,
      'isDown':true,
      'startFrame':696
   },
   {
      'frame':697,
      'button':7,
      'isDown':false,
      'startFrame':697
   },
   {
      'frame':698,
      'button':0,
      'isDown':true,
      'startFrame':698
   },
   {
      'frame':700,
      'button':0,
      'isDown':false,
      'startFrame':700
   },
   {
      'frame':744,
      'button':7,
      'isDown':true,
      'startFrame':744
   },
   {
      'frame':745,
      'button':7,
      'isDown':false,
      'startFrame':745
   },
   {
      'frame':747,
      'button':7,
      'isDown':true,
      'startFrame':747
   },
   {
      'frame':747,
      'button':7,
      'isDown':false,
      'startFrame':747
   },
   {
      'frame':749,
      'button':7,
      'isDown':true,
      'startFrame':749
   },
   {
      'frame':750,
      'button':7,
      'isDown':false,
      'startFrame':750
   },
   {
      'frame':756,
      'button':0,
      'isDown':true,
      'startFrame':756
   },
   {
      'frame':758,
      'button':0,
      'isDown':false,
      'startFrame':758
   },
   {
      'frame':762,
      'button':7,
      'isDown':true,
      'startFrame':762
   },
   {
      'frame':762,
      'button':7,
      'isDown':false,
      'startFrame':762
   },
   {
      'frame':774,
      'button':7,
      'isDown':true,
      'startFrame':774
   },
   {
      'frame':775,
      'button':7,
      'isDown':false,
      'startFrame':775
   },
   {
      'frame':788,
      'button':0,
      'isDown':true,
      'startFrame':788
   },
   {
      'frame':790,
      'button':7,
      'isDown':true,
      'startFrame':790
   },
   {
      'frame':790,
      'button':0,
      'isDown':false,
      'startFrame':790
   },
   {
      'frame':791,
      'button':7,
      'isDown':false,
      'startFrame':791
   },
   {
      'frame':792,
      'button':7,
      'isDown':true,
      'startFrame':792
   },
   {
      'frame':793,
      'button':7,
      'isDown':false,
      'startFrame':793
   },
   {
      'frame':794,
      'button':7,
      'isDown':true,
      'startFrame':794
   },
   {
      'frame':795,
      'button':7,
      'isDown':false,
      'startFrame':795
   },
   {
      'frame':797,
      'button':7,
      'isDown':true,
      'startFrame':797
   },
   {
      'frame':797,
      'button':7,
      'isDown':false,
      'startFrame':797
   },
   {
      'frame':799,
      'button':7,
      'isDown':true,
      'startFrame':799
   },
   {
      'frame':800,
      'button':7,
      'isDown':false,
      'startFrame':800
   },
   {
      'frame':801,
      'button':2,
      'isDown':false,
      'startFrame':801
   },
   {
      'frame':802,
      'button':2,
      'isDown':false,
      'startFrame':802
   },
   {
      'frame':803,
      'button':2,
      'isDown':false,
      'startFrame':803
   },
   {
      'frame':804,
      'button':2,
      'isDown':false,
      'startFrame':804
   },
   {
      'frame':805,
      'button':2,
      'isDown':false,
      'startFrame':805
   },
   {
      'frame':806,
      'button':2,
      'isDown':false,
      'startFrame':806
   },
   {
      'frame':807,
      'button':2,
      'isDown':false,
      'startFrame':807
   },
   {
      'frame':808,
      'button':2,
      'isDown':false,
      'startFrame':808
   },
   {
      'frame':809,
      'button':2,
      'isDown':false,
      'startFrame':809
   },
   {
      'frame':810,
      'button':2,
      'isDown':false,
      'startFrame':810
   },
   {
      'frame':811,
      'button':2,
      'isDown':false,
      'startFrame':811
   },
   {
      'frame':812,
      'button':2,
      'isDown':false,
      'startFrame':812
   },
   {
      'frame':813,
      'button':2,
      'isDown':false,
      'startFrame':813
   },
   {
      'frame':814,
      'button':2,
      'isDown':false,
      'startFrame':814
   },
   {
      'frame':818,
      'button':DemoButton.BUTTON_LEFT,
      'isDown':true,
      'startFrame':814
   },
   {
      'frame':840,
      'button':DemoButton.BUTTON_A,
      'isDown':true,
      'startFrame':814
   },
   {
      'frame':841,
      'button':DemoButton.BUTTON_A,
      'isDown':false,
      'startFrame':814
   }
]