import { DemoEntry, DemoButton } from '../IDemoPlayer';
import { eventsForSinglePress } from './utility';

// This demonstrates that SIDEWAYS comes BEFORE ROTATE

export function getSidewaysVsRotate() {
  return sidewaysVsRotate
    .concat(eventsForSinglePress(DemoButton.BUTTON_A, 745))
    .concat(eventsForSinglePress(DemoButton.BUTTON_LEFT, 748))
    .concat(eventsForSinglePress(DemoButton.BUTTON_LEFT, 759))
    .concat(eventsForSinglePress(DemoButton.BUTTON_LEFT, 762))
    .concat(eventsForSinglePress(DemoButton.BUTTON_B, 790))
    .concat(eventsForSinglePress(DemoButton.BUTTON_RIGHT, 790));
}

const sidewaysVsRotate: DemoEntry[] = [
  {
     'frame':270,
     'button':3,
     'isDown':true,
     'startFrame':270
  },
  {
     'frame':271,
     'button':3,
     'isDown':false,
     'startFrame':271
  },
  {
     'frame':275,
     'button':3,
     'isDown':true,
     'startFrame':275
  },
  {
     'frame':276,
     'button':3,
     'isDown':false,
     'startFrame':276
  },
  {
     'frame':280,
     'button':3,
     'isDown':true,
     'startFrame':280
  },
  {
     'frame':281,
     'button':3,
     'isDown':false,
     'startFrame':281
  },
  {
     'frame':285,
     'button':7,
     'isDown':true,
     'startFrame':285
  },
  {
     'frame':286,
     'button':7,
     'isDown':false,
     'startFrame':286
  },
  {
     'frame':290,
     'button':7,
     'isDown':true,
     'startFrame':290
  },
  {
     'frame':291,
     'button':7,
     'isDown':false,
     'startFrame':291
  },
  {
     'frame':295,
     'button':7,
     'isDown':true,
     'startFrame':295
  },
  {
     'frame':296,
     'button':7,
     'isDown':false,
     'startFrame':296
  },
  {
     'frame':300,
     'button':5,
     'isDown':true,
     'startFrame':300
  },
  {
     'frame':301,
     'button':5,
     'isDown':false,
     'startFrame':301
  },
  {
     'frame':305,
     'button':0,
     'isDown':true,
     'startFrame':305
  },
  {
     'frame':306,
     'button':3,
     'isDown':true,
     'startFrame':306
  },
  {
     'frame':312,
     'button':0,
     'isDown':false,
     'startFrame':312
  },
  {
     'frame':312,
     'button':3,
     'isDown':false,
     'startFrame':312
  },
  {
     'frame':478,
     'button':6,
     'isDown':true,
     'startFrame':478
  },
  {
     'frame':479,
     'button':0,
     'isDown':true,
     'startFrame':479
  },
  {
     'frame':479,
     'button':6,
     'isDown':false,
     'startFrame':479
  },
  {
     'frame':481,
     'button':6,
     'isDown':true,
     'startFrame':481
  },
  {
     'frame':481,
     'button':0,
     'isDown':false,
     'startFrame':481
  },
  {
     'frame':482,
     'button':6,
     'isDown':false,
     'startFrame':482
  },
  {
     'frame':483,
     'button':6,
     'isDown':true,
     'startFrame':483
  },
  {
     'frame':484,
     'button':6,
     'isDown':false,
     'startFrame':484
  },
  {
     'frame':485,
     'button':6,
     'isDown':true,
     'startFrame':485
  },
  {
     'frame':486,
     'button':6,
     'isDown':false,
     'startFrame':486
  },
  {
     'frame':487,
     'button':6,
     'isDown':true,
     'startFrame':487
  },
  {
     'frame':488,
     'button':6,
     'isDown':false,
     'startFrame':488
  },
  {
     'frame':490,
     'button':6,
     'isDown':true,
     'startFrame':490
  },
  {
     'frame':490,
     'button':6,
     'isDown':false,
     'startFrame':490
  },
  {
     'frame':545,
     'button':0,
     'isDown':true,
     'startFrame':545
  },
  {
     'frame':546,
     'button':6,
     'isDown':true,
     'startFrame':546
  },
  {
     'frame':547,
     'button':0,
     'isDown':false,
     'startFrame':547
  },
  {
     'frame':547,
     'button':6,
     'isDown':false,
     'startFrame':547
  },
  {
     'frame':612,
     'button':0,
     'isDown':true,
     'startFrame':612
  },
  {
     'frame':612,
     'button':7,
     'isDown':true,
     'startFrame':612
  },
  {
     'frame':614,
     'button':0,
     'isDown':false,
     'startFrame':614
  },
  {
     'frame':614,
     'button':7,
     'isDown':false,
     'startFrame':614
  },
  {
     'frame':615,
     'button':7,
     'isDown':true,
     'startFrame':615
  },
  {
     'frame':616,
     'button':7,
     'isDown':false,
     'startFrame':616
  },
  {
     'frame':618,
     'button':7,
     'isDown':true,
     'startFrame':618
  },
  {
     'frame':619,
     'button':7,
     'isDown':false,
     'startFrame':619
  },
  {
     'frame':661,
     'button':6,
     'isDown':true,
     'startFrame':661
  },
  {
     'frame':662,
     'button':6,
     'isDown':false,
     'startFrame':662
  },
  {
     'frame':678,
     'button':0,
     'isDown':true,
     'startFrame':678
  },
  {
     'frame':679,
     'button':7,
     'isDown':true,
     'startFrame':679
  },
  {
     'frame':680,
     'button':0,
     'isDown':false,
     'startFrame':680
  },
  {
     'frame':680,
     'button':7,
     'isDown':false,
     'startFrame':680
  },
  {
     'frame':682,
     'button':7,
     'isDown':true,
     'startFrame':682
  },
  {
     'frame':683,
     'button':7,
     'isDown':false,
     'startFrame':683
  },
  {
     'frame':685,
     'button':7,
     'isDown':true,
     'startFrame':685
  },
  {
     'frame':686,
     'button':7,
     'isDown':false,
     'startFrame':686
  },
  {
     'frame':687,
     'button':2,
     'isDown':false,
     'startFrame':687
  },
  {
     'frame':688,
     'button':2,
     'isDown':false,
     'startFrame':688
  },
  {
     'frame':689,
     'button':2,
     'isDown':false,
     'startFrame':689
  },
  {
     'frame':690,
     'button':2,
     'isDown':false,
     'startFrame':690
  },
  {
     'frame':691,
     'button':2,
     'isDown':false,
     'startFrame':691
  },
  {
     'frame':692,
     'button':2,
     'isDown':false,
     'startFrame':692
  },
  {
     'frame':693,
     'button':2,
     'isDown':false,
     'startFrame':693
  },
  {
     'frame':694,
     'button':2,
     'isDown':false,
     'startFrame':694
  },
  {
     'frame':695,
     'button':2,
     'isDown':false,
     'startFrame':695
  },
  {
     'frame':696,
     'button':2,
     'isDown':false,
     'startFrame':696
  },
  {
     'frame':697,
     'button':2,
     'isDown':false,
     'startFrame':697
  },
  {
     'frame':698,
     'button':2,
     'isDown':false,
     'startFrame':698
  },
  {
     'frame':699,
     'button':2,
     'isDown':false,
     'startFrame':699
  },
  {
     'frame':700,
     'button':2,
     'isDown':false,
     'startFrame':700
  },
  {
     'frame':701,
     'button':2,
     'isDown':false,
     'startFrame':701
  },
  {
     'frame':702,
     'button':2,
     'isDown':false,
     'startFrame':702
  },
  {
     'frame':703,
     'button':2,
     'isDown':false,
     'startFrame':703
  },
  {
     'frame':704,
     'button':2,
     'isDown':false,
     'startFrame':704
  },
  {
     'frame':705,
     'button':2,
     'isDown':false,
     'startFrame':705
  },
  {
     'frame':706,
     'button':2,
     'isDown':false,
     'startFrame':706
  },
  {
     'frame':707,
     'button':2,
     'isDown':false,
     'startFrame':707
  },
  {
     'frame':708,
     'button':2,
     'isDown':false,
     'startFrame':708
  },
  {
     'frame':709,
     'button':2,
     'isDown':false,
     'startFrame':709
  },
  {
     'frame':710,
     'button':2,
     'isDown':false,
     'startFrame':710
  },
  {
     'frame':711,
     'button':2,
     'isDown':false,
     'startFrame':711
  },
  {
     'frame':712,
     'button':2,
     'isDown':false,
     'startFrame':712
  },
  {
     'frame':713,
     'button':2,
     'isDown':false,
     'startFrame':713
  },
  {
     'frame':714,
     'button':2,
     'isDown':false,
     'startFrame':714
  },
  {
     'frame':715,
     'button':2,
     'isDown':false,
     'startFrame':715
  },
  {
     'frame':716,
     'button':2,
     'isDown':false,
     'startFrame':716
  },
  {
     'frame':717,
     'button':2,
     'isDown':false,
     'startFrame':717
  },
  {
     'frame':718,
     'button':2,
     'isDown':false,
     'startFrame':718
  },
  {
     'frame':719,
     'button':2,
     'isDown':false,
     'startFrame':719
  },
  {
     'frame':720,
     'button':2,
     'isDown':false,
     'startFrame':720
  },
  {
     'frame':721,
     'button':2,
     'isDown':false,
     'startFrame':721
  },
  {
     'frame':722,
     'button':2,
     'isDown':false,
     'startFrame':722
  },
  {
     'frame':723,
     'button':2,
     'isDown':false,
     'startFrame':723
  },
  {
     'frame':724,
     'button':2,
     'isDown':false,
     'startFrame':724
  },
  {
     'frame':725,
     'button':2,
     'isDown':false,
     'startFrame':725
  },
  {
     'frame':726,
     'button':2,
     'isDown':false,
     'startFrame':726
  },
  {
     'frame':727,
     'button':2,
     'isDown':false,
     'startFrame':727
  },
  {
     'frame':728,
     'button':2,
     'isDown':false,
     'startFrame':728
  },
  {
     'frame':729,
     'button':2,
     'isDown':false,
     'startFrame':729
  },
  {
     'frame':730,
     'button':2,
     'isDown':false,
     'startFrame':730
  },
  {
     'frame':731,
     'button':2,
     'isDown':false,
     'startFrame':731
  },
  {
     'frame':732,
     'button':2,
     'isDown':false,
     'startFrame':732
  },
  {
     'frame':733,
     'button':2,
     'isDown':false,
     'startFrame':733
  },
  {
     'frame':734,
     'button':2,
     'isDown':false,
     'startFrame':734
  },
  {
     'frame':735,
     'button':2,
     'isDown':false,
     'startFrame':735
  },
  {
     'frame':736,
     'button':2,
     'isDown':false,
     'startFrame':736
  },
  {
     'frame':737,
     'button':2,
     'isDown':false,
     'startFrame':737
  },
  {
     'frame':738,
     'button':2,
     'isDown':false,
     'startFrame':738
  },
  {
     'frame':739,
     'button':2,
     'isDown':false,
     'startFrame':739
  },
  {
     'frame':740,
     'button':2,
     'isDown':false,
     'startFrame':740
  },
  {
     'frame':741,
     'button':2,
     'isDown':false,
     'startFrame':741
  },
  {
     'frame':742,
     'button':2,
     'isDown':false,
     'startFrame':742
  },
  {
     'frame':743,
     'button':2,
     'isDown':false,
     'startFrame':743
  }
];