
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_github_nelhage_rules_boost",
    commit = "9f9fb8b2f0213989247c9d5c0e814a8451d18d7f",
    remote = "https://github.com/nelhage/rules_boost",
    shallow_since = "1570056263 -0700",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()


load("//third_party:repo.bzl", "tf_http_archive")
load("//third_party/py:python_configure.bzl", "python_configure")

tf_http_archive(
    name = "pybind11",
    urls = [
        "https://mirror.bazel.build/github.com/pybind/pybind11/archive/v2.2.4.tar.gz",
        "https://github.com/pybind/pybind11/archive/v2.2.4.tar.gz",
    ],
    sha256 = "b69e83658513215b8d1443544d0549b7d231b9f201f6fc787a2b2218b408181e",
    strip_prefix = "pybind11-2.2.4",
    build_file = str("//third_party:pybind11.BUILD"),
)

python_configure(name = "local_config_python")