#include "src/shared/MoveEvaluator/MoveEvaluatorGroup.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluator.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorAdapter.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorTetrisReady.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBlockLinear.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBlockQuadratic.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorEdgeWell.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorWellVeryLeft.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorWellLoc.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBottomLoc.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBlockBothLinear.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBlockBothAdvLinear.hpp"
#include "src/shared/MoveEvaluator/Evaluators/MoveEvaluatorBlockBothAdvLinearVar.hpp"

