#!/usr/bin/env bash
set -e;
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd ../cpp; bazel build //src/pso/main:get_moves --cxxopt="-O3" --cxxopt="-DNDEBUG"
#frompath="${DIR}/../cpp/bazel-bin/src/pso/main/get_moves"
#topath="${DIR}/external_bin/get_moves"
#sudo cp "${frompath}" "${topath}"
#echo "Copied $frompath --> $topath"
